# Generated by Django 3.2 on 2023-01-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20230126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Черный'), ('White', 'Белый'), ('Ginger', 'Рыжий'), ('Mixed', 'Смешаный'), ('Brown', 'Коричневый')], max_length=16),
        ),
    ]
